### ISSUE TITLE
Salut ! :)

### ISSUE THREAD

**Issue by ZeFurtif** [Ilade-s/apiecoledirecte#4]
Salut Raphaël !
Je suis aussi un élève de spé NSI, et je voulais integrer ton api à mon bot discord.
Je n'arrive pas a recuperer l'emploi du temps. Ton aide serait appréciée.

Tu peux me mp sur Discord : ZeFurtif#1935

Merci d'avance :)

**Comment by Ilade-s** [comment]
Salut !
Tu peux l'intégrer, même si pour le moment elle n'inclut que le login (je compte faire l'emploi du temps d'ici peu du coup)
Je veux bien t'aider, mais je n'arrive pas à t'envoyer une demande d'ami (erreur d'orthographe ?) essaye de me mp : ilade#7377

**Comment by Ilade-s** [comment]
j'ai terminé la fonction fetch_schedule qui te retourne l'emploi du temps, tu peux la tester pour voir si elle correspond à ce que tu voulais @ZeFurtif
