### ISSUE TITLE
commen récuperez le calendrier

### ISSUE THREAD

**Issue by micuit-cuit** [Ilade-s/apiecoledirecte#7]
commen on récuper le calendrier et les devoir

**Comment by Ilade-s** [comment]
Salut, il faudra utiliser fetch_schedule pour le calendrier, et fetch_work pour les devoirs (Par contre pour le calendrier, ça va renvoyer l'emploi du temps de la semaine en cours uniquement, mais si c'est une problème dit moi).
Pour voir comment appeler la classe et ses fonctions, tu peux regarder à la fin du fichier python 
(dans le `if __name__ == '__main__'`). 
Les fonctions renvoient alors : 
- fetch_schedule : un dictionnaire des jours de la semaine, avec pour chaque la liste des cours de la journée du plus tôt au plus tard
- fetch_work : une liste des devoirs, sous forme de dictionnaires, qui sont soit tel quels venant de L’API d'école directe, ou bien simplifié, comme expliqué dans la documentation de la fonction @yupa42
